services:
  mongo:
    image: mongo:7
    container_name: job-min-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  app:
    build: .
    container_name: job-min-app
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=jobsdb
      - MONGO_COLL=jobs
      - HTTP_ADDR=:8080
    ports:
      - "8080:8080"


volumes:
  mongo-data: